language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
os:
    - linux
before_install:
    - pip3 install --upgrade pip
install:
    - pip install -r requirements.txt
#     don't use the line below because codecov generates a false 'miss'
#     - pip install . --use-feature=in-tree-build
    - pip install -e .
script:
    # - pytest tests
    - coverage run -m pytest tests
    - coverage xml
after_success:
#  - bash <(curl -s https://codecov.io/bash)
    - bash <(curl -Os https://uploader.codecov.io/latest/linux/codecov)
    - bash <(chmod +x codecov)
    - ./codecov
