language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
# os:
#     - linux
#     - osx
#     - windows
before_install:
    - pip3 install --upgrade pip

install:
    - pip install -r requirements.txt
    - pip install .
    - pip install pytest
    - pip install codecov
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
script:
    - pytest tests
    - coverage run --source=sqlalchemyseed -m pytest tests
after_success:
#  - bash <(curl -s https://codecov.io/bash)
  - codecov
