language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
os:
    - linux
    - osx
    - windows
before_install:
    - python -m pip install --upgrade pip

install:
    - pip install -r requirements.txt
    - pip install .
    - pip install pytest
script:
    - pytest
