language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

before_install:
    - py -m pip install --upgrade pip

install:
    - pip install -r requirements.txt
    - pip install .
    - pip install pytest
script:
    - pytest
